#FROM gradle:jdk8 AS build
#WORKDIR /app
#COPY . .
#RUN /app/gradlew build

#
# Package stage
#
FROM openjdk:8-jre
#COPY --from=build /app/build/libs/easy-movie-0.0.1-SNAPSHOT.jar /usr/local/lib/app.jar
COPY build/libs/easy-movie-0.0.1-SNAPSHOT.jar /usr/local/lib/app.jar
HEALTHCHECK CMD curl -fs http://localhost:8080/api/ping || exit 1
ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar", "--spring.profiles.active=dev"]
