version: "3"
services:
  dom:
    container_name: easy-movie-dom
    image: "registry.cn-shenzhen.aliyuncs.com/xinze517/easy-movie-dom:${COMMIT:-commit}"
    ports:
      - "28080:8080"
    networks:
      - easy-movie-net
networks:
  easy-movie-net:
    external: true