spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true