name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Execute Gradle Coverage
        run: ./gradlew check

      - name: Build Docker Image
        run: |
          sha="${{ github.event.pull_request.head.sha }}"
          commit=${sha: 0: 7}
          docker build . --file Dockerfile --tag easy-movie-dom:$commit
      - name: Push To Ali Cloud
        run: |
          sha="${{ github.event.pull_request.head.sha }}"
          commit=${sha: 0: 7}
          repo_user="${{ secrets.DOCKER_REPOSITORY_USER }}"
          docker login --username=$repo_user -p bPVj1TLvBR2CLYI5uE0n registry.cn-shenzhen.aliyuncs.com
          docker tag easy-movie-dom:$commit registry.cn-shenzhen.aliyuncs.com/$repo_user/easy-movie-dom:$commit
          docker push registry.cn-shenzhen.aliyuncs.com/$repo_user/easy-movie-dom:$commit
      - name: Deploy On My Sever
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            sha="${{ github.event.pull_request.head.sha }}"
            commit=${sha: 0: 7}
            repo_user="${{ secrets.DOCKER_REPOSITORY_USER }}"
            cd /home/${{ secrets.DEPLOY_USER }}/easy-movie/dom
            docker-compose down
            docker login --username=$repo_user -p bPVj1TLvBR2CLYI5uE0n registry.cn-shenzhen.aliyuncs.com >/dev/null 2>&1
            docker pull registry.cn-shenzhen.aliyuncs.com/$repo_user/easy-movie-dom:$commit
            COMMIT=$commit docker-compose up -d
